import pytest

from myriapod.report import (
    ReportError,
    parse_inline,
    parse_markdown,
    save_report,
)

CONTENT = """# Titre principal

Un paragraphe avec du **gras**, de l'*italique* et du `code_inline`,
réparti sur deux lignes source.

## Section

- premier point — avec un tiret cadratin
  - sous-point avec `snake_case_intact`
- second point

> une citation

```python
x = build_swarm(planner_model="openai:gpt-5")
```

---

Voir [la doc](https://ai.pydantic.dev) pour la suite.
"""

META = [("Generated by", "myriapod test"), ("Cost", "$0.0210")]


def test_parse_inline_splits_emphasis_and_keeps_underscores():
    spans = parse_inline("du **gras**, de l'*italique*, `snake_case_id` et rien")
    assert [(s.text, s.bold, s.italic, s.code) for s in spans if s.text.strip()] == [
        ("du ", False, False, False),
        ("gras", True, False, False),
        (", de l'", False, False, False),
        ("italique", False, True, False),
        (", ", False, False, False),
        ("snake_case_id", False, False, True),
        (" et rien", False, False, False),
    ]


def test_parse_inline_flattens_links():
    assert parse_inline("voir [la doc](https://x.dev) ici")[0].text == (
        "voir la doc (https://x.dev) ici"
    )


def test_parse_markdown_block_kinds():
    kinds = [(b.kind, b.level) for b in parse_markdown(CONTENT)]
    assert ("heading", 1) in kinds
    assert ("heading", 2) in kinds
    assert ("bullet", 0) in kinds
    assert ("bullet", 1) in kinds  # nested
    assert ("code", 0) in kinds
    assert ("rule", 0) in kinds
    # soft-wrapped source lines join into a single paragraph
    paras = [b for b in parse_markdown(CONTENT) if b.kind == "para"]
    assert any("réparti sur deux lignes" in p.plain for p in paras)


TABLE = """## Offres

| Idée | Prix | Délai |
| --- | ---: | :--- |
| Audit-éclair | 4 900 € | 2 semaines |
| **Abonnement** | 3 k€/mois | 1 mois |

Un paragraphe | avec un pipe qui n'ouvre pas de tableau.
"""


def test_parse_markdown_reads_a_pipe_table():
    blocks = parse_markdown(TABLE)
    tables = [b for b in blocks if b.kind == "table"]
    assert len(tables) == 1
    rows = [["".join(s.text for s in cell) for cell in row] for row in tables[0].rows]
    assert rows[0] == ["Idée", "Prix", "Délai"]          # header, separator dropped
    assert rows[2] == ["Abonnement", "3 k€/mois", "1 mois"]
    assert tables[0].rows[2][0][0].bold                  # emphasis survives in cells
    # a lone pipe in prose is not a table: it stays a paragraph
    assert any(b.kind == "para" and "pipe qui n'ouvre pas" in b.plain for b in blocks)


def test_table_rows_become_slide_bullets(tmp_path):
    pptx = pytest.importorskip("pptx")
    path = save_report(tmp_path / "deck.pptx", TABLE, title="T")
    text = "\n".join(
        shape.text_frame.text
        for slide in pptx.Presentation(str(path)).slides
        for shape in slide.shapes
        if shape.has_text_frame
    )
    assert "Idée: Audit-éclair · Prix: 4 900 € · Délai: 2 semaines" in text


def test_parse_markdown_survives_unclosed_fence():
    blocks = parse_markdown("texte\n\n```\njamais fermé")
    assert [b.kind for b in blocks] == ["para", "code"]


@pytest.mark.parametrize("ext", [".md", ".txt", ".pdf", ".pptx"])
def test_save_report_writes_every_format(tmp_path, ext):
    out = save_report(tmp_path / f"r{ext}", CONTENT, title="Titre", meta=META)
    assert out.exists() and out.stat().st_size > 0


def test_markdown_keeps_content_verbatim_and_adds_provenance(tmp_path):
    out = save_report(tmp_path / "r.md", CONTENT, title="Titre", meta=META)
    written = out.read_text(encoding="utf-8")
    assert "**gras**" in written  # untouched
    assert "Cost: $0.0210" in written


def test_save_report_creates_parent_directory(tmp_path):
    out = save_report(tmp_path / "deep" / "nested" / "r.md", "hello")
    assert out.exists()


def test_save_report_rejects_unknown_suffix(tmp_path):
    with pytest.raises(ReportError, match=r"\.docx"):
        save_report(tmp_path / "r.docx", CONTENT)
    with pytest.raises(ReportError):
        save_report(tmp_path / "noext", CONTENT)


def test_pdf_has_a_pdf_header(tmp_path):
    out = save_report(tmp_path / "r.pdf", CONTENT, title="Titre é—", meta=META)
    assert out.read_bytes().startswith(b"%PDF")


def test_pptx_splits_slides_on_top_level_headings(tmp_path):
    pptx = pytest.importorskip("pptx")
    out = save_report(tmp_path / "r.pptx", CONTENT, title="Titre", meta=META)
    prs = pptx.Presentation(str(out))
    titles = [s.shapes.title.text for s in prs.slides]
    assert titles[0] == "Titre"                 # cover
    assert "Titre principal" in titles
    assert "Section" in titles


def test_markdown_does_not_double_the_footer_rule(tmp_path):
    out = save_report(tmp_path / "r.md", "Corps du rapport.\n\n---\n", meta=META)
    body = out.read_text(encoding="utf-8")
    assert "---\n\n---" not in body
    assert body.count("---") == 1


def test_title_is_dropped_when_the_answer_has_its_own(tmp_path):
    with_h1 = save_report(tmp_path / "a.md", "# Vrai titre\n\ntexte", title="la question")
    assert "la question" not in with_h1.read_text(encoding="utf-8")

    without_h1 = save_report(tmp_path / "b.md", "## Section\n\ntexte", title="la question")
    assert without_h1.read_text(encoding="utf-8").startswith("# la question")
